BeeBilisim.Web/Controllers/AdminPanelController.cs
using BeeBilisim.Web.Helpers;
using BeeBilisim.Web.Models;
using BeeBilisim.Web.Services;
using Hash;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using MimeKit;
using Newtonsoft.Json;
using System.IO;
using System.Net.Mail;
using System.Security;
using System.Security.Claims;
using System.Web;
using System.Xml.Linq;
using SmtpClient = MailKit.Net.Smtp.SmtpClient;

namespace BeeBilisim.Web.Controllers
{
    public class AdminPanelController : Controller
    {

        private readonly BeeDbContext _dbContext;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment;
        public AdminPanelController(BeeDbContext dbContext, Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _dbContext = dbContext;
            this.hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {

            return View();
        }
        //KULLANICI İŞLEMLERİ
        #region Kisi Bilgileri(User)
        [HttpGet]
        public IActionResult KisiBilgileri()
        {
            var kullaniciAdi = HttpContext.User.Identity.Name;
            var kullanici = _dbContext.Kullanicilars.FirstOrDefault(q => q.Ad == kullaniciAdi);

            ViewBag.Kullanici = kullanici;

            var kisiler = _dbContext.Kullanicilars.Where(x=>x.Aktif==true).ToList();
            return View(kisiler);
        }

        public IActionResult KisiSil(int id)
        {
            var silinecekKisi = _dbContext.Kullanicilars.Where(x => x.Id == id).FirstOrDefault();
            var identity = (ClaimsIdentity)User.Identity;
            var role = identity.FindFirst(ClaimTypes.Email).Value;

            silinecekKisi.DeletedUser = role;
            silinecekKisi.Aktif = false;
            
            if(silinecekKisi.DeletedUser!=null|| silinecekKisi.DeletedUser != "")
            {
                silinecekKisi.DeletedDate = DateTime.Now;
            }

            _dbContext.SaveChanges();
            return RedirectToAction("KisiBilgileri");
        }

        public IActionResult KisiGetir(int id)
        {
            var d = _dbContext.Kullanicilars.Find(id);
            return View("KisiGetir", d);
        }

        [HttpPost]
        public IActionResult KisiGuncelle(Kullanicilars admin)
        {
            var x = _dbContext.Kullanicilars.FirstOrDefault(a => a.Id == admin.Id);
            x.Id = admin.Id;
            x.Ad = admin.Ad;
            x.Soyad = admin.Soyad;
            x.Email = admin.Email;
            x.LastupUser = admin.LastupUser;
           
            if(admin.LastupUser!=null || x.LastupUser != "")
            {
                x.LastupDate = DateTime.Now;
            }


            if(admin.Sifre==null || admin.Sifre2==null) {
                goto A;
            }
            x.Sifre = Sifreleme.sha1(admin.Sifre.Trim());
            x.Sifre2 = Sifreleme.sha1(admin.Sifre2.Trim());

            if (x.Sifre != x.Sifre2)
            {
                ViewBag.hata = "Şifreler uyuşmuyor. Lütfen tekrar deneyin!";
                return View("KisiGetir", admin);
            }
            A:
            x.Telefon = admin.Telefon;
            _dbContext.SaveChanges();
            return RedirectToAction("KisiBilgileri");
        }

        [HttpGet]
        public IActionResult YeniKisiEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult YeniKisiEkle(Kullanicilars admin)
        {
            admin.Sifre= Sifreleme.sha1(admin.Sifre.Trim());
            admin.Sifre2= Sifreleme.sha1(admin.Sifre2.Trim());

            if (admin.Sifre != admin.Sifre2)
            {
                ViewBag.hata = "Şifreler uyuşmuyor. Lütfen tekrar giriniz.";
                return View();
            }


            admin.Aktif = true;
            admin.Catalog = "";
            admin.CreatedDate = DateTime.Now;
            admin.DeletedDate = null;
            admin.DeletedUser = "";
            admin.Entegrasyon = "";
            admin.FlagTipi = 0;
            admin.Kilitli = false;
            admin.LastupDate = null;
            admin.LastupUser = "";
            admin.Special1 = "";
            admin.Special2 = "";
            admin.Special3 = "";
            admin.İptal = false;

            _dbContext.Kullanicilars.Add(admin);
            _dbContext.SaveChanges();
            return RedirectToAction("KisiBilgileri");
        }
        #endregion

        //ANA SAYFA
        #region Slider Bilgileri
        public IActionResult SliderListesi()
        {
            var sliderlar = _dbContext.AnaSayfaSliderModels.OrderBy(x => x.Sira).ToList();
            return View(sliderlar);
        }

        [HttpGet]
        public IActionResult YeniSliderEkle()
        {
            return View();
        }

        [HttpPost]
        public IActionResult YeniSliderEkle(AnaSayfaSliderModel slider)
        {
            _dbContext.AnaSayfaSliderModels.Add(slider);
            _dbContext.SaveChanges();
            return RedirectToAction("SliderListesi");

            //string fileName = Guid.NewGuid().ToString();
            //if (Getfile != null)
            //{
            //    var Upload = Path.Combine(_environment.WebRootPath, "Dosya Yolu", fileName);
            //    Getfile.CopyTo(new FileStream(Upload, FileMode.Create));

            //}
            //_dbContext.AnaSayfaSliderModels.Add(Getfile;
            //_dbContext.SaveChanges();
            //return RedirectToAction("SliderListesi");

        }
        public IActionResult SliderSil(int id)
        {
            var silinecekSlider = _dbContext.AnaSayfaSliderModels.Where(x => x.Id == id).FirstOrDefault();
            _dbContext.AnaSayfaSliderModels.Remove(silinecekSlider);
            _dbContext.SaveChanges();

            return RedirectToAction("SliderListesi");
        }

        //ID'YE GÖRE KİŞİ GETİRME
        public IActionResult SliderGetir(int id)
        {
            var d = _dbContext.AnaSayfaSliderModels.Find(id);
            return View("SliderGetir", d);
        }

        [HttpPost]
        public IActionResult SliderGuncelle(AnaSayfaSliderModel slider)
        {
            var x = _dbContext.AnaSayfaSliderModels.FirstOrDefault(a => a.Id == slider.Id);
            x.Id = slider.Id;
            x.FotoUrl = slider.FotoUrl;
            x.Sira = slider.Sira;

            _dbContext.SaveChanges();
            return RedirectToAction("SliderListesi");
        }
        #endregion

        #region Referans Bilgileri
        public IActionResult ReferansListesi()
        {
            var referanslar = _dbContext.ReferasanslarModels.OrderBy(x => x.Sira).Where(x=>x.Aktif==true).ToList();
            return View(referanslar);
        }
        public async Task<IActionResult> ReferansSil(int id)
        {
            var silinecekReferans = await _dbContext.ReferasanslarModels.FindAsync(id);
            var identity = (ClaimsIdentity)User.Identity;
            var role = identity.FindFirst(ClaimTypes.Email).Value;

            var imagePath = Path.Combine(hostingEnvironment.WebRootPath, "images", silinecekReferans.ImageName);
            if (System.IO.File.Exists(imagePath)) 
                System.IO.File.Delete(imagePath);

            silinecekReferans.DeletedUser = role;
            silinecekReferans.Aktif = false;
            if (silinecekReferans.DeletedUser != null || silinecekReferans.DeletedUser != "")
            {
                silinecekReferans.DeletedDate = DateTime.Now;
            }

            await _dbContext.SaveChangesAsync();
            return RedirectToAction("ReferansListesi");
        }

        public IActionResult ReferansEkle()
        {
            var deger = _dbContext.ReferasanslarModels.Select(x => x.Sira).DefaultIfEmpty().Max();
            ViewBag.SonSira = deger + 1;
            return View(new ReferasanslarModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReferansEkle(ReferasanslarModel model)
        {
            var deger = _dbContext.ReferasanslarModels.Select(x => x.Sira).DefaultIfEmpty().Max();
            ViewBag.SonSira = deger + 1;
            model.Aktif = true;
            model.Catalog = "";
            model.CreatedDate = DateTime.Now;
            model.DeletedDate = null;
            model.DeletedUser = "";
            model.Entegrasyon = "";
            model.FlagTipi = 0;
            model.Kilitli = false;
            model.LastupDate = null;
            model.LastupUser = "";
            model.Special1 = "";
            model.Special2 = "";
            model.Special3 = "";
            model.İptal = false;
            if (ModelState.IsValid)
            {
                //Save image to wwroot/image
                string wwwRootPath = hostingEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                string extension = Path.GetExtension(model.ImageFile.FileName);
                model.ImageName = fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                string path = Path.Combine(wwwRootPath + "/images/", fileName);
                using(var fileStream=new FileStream(path, FileMode.Create))
                {
                    await model.ImageFile.CopyToAsync(fileStream);
                }
                //Insert to database

BeeBilisim.Web/Views/AdminPanel/GenelDuzenleme.cshtml
@using BeeBilisim.Web.Models
@model List<AnasayfaModel>

@{
    ViewData["Title"] = "GenelDuzenleme";
    Layout = "~/Views/Shared/_AdminPanelLayout.cshtml";
}



    <partial name="SloganGoruntulePartial" />
    <partial name="TelefonFaxEmailGoruntule" />
    <partial name="GovdeMetniGoruntule" />
    <partial name="NedenBizGoruntule" />



BeeBilisim.Web/Views/AdminPanel/GovdeMetniGoruntule.cshtml
@using BeeBilisim.Web.Models
@model List<AnasayfaModel>
@{
    Layout = "";

}

<br>
<h2 class="text-center">GÖVDE METNİ BİLGİSİ</h2>
<br />
<table class="table table-bordered col-md-12" >
    <thead>
        <tr>
            <th scope="col">Başlık</th>
            <th scope="col">Açıklama 1(Sol Taraf)</th>
            <th scope="col">Açıklama 2(Sağ Taraf)</th>
            <th scope="col" >Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.GovdeMetinBasligi</td>
                <td>@x.GovdeMetinAciklama1</td>
                <td>@x.GovdeMetinAciklama2</td>
                <td ><a href="/AdminPanel/GovdeMetniGetir/@x.Id" class="btn btn-warning text-center">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>


BeeBilisim.Web/Views/AdminPanel/IletisimGenelDuzenleme.cshtml
@using BeeBilisim.Web.Models
@model List<IletisimModel>
@{
    ViewData["Title"] = "IletisimGenelDuzenleme";
    Layout = "~/Views/Shared/_AdminPanelLayout.cshtml";
}

    <partial name="IletisimPartial" />

BeeBilisim.Web/Views/AdminPanel/KendimiziTanitalimPartial.cshtml
@using BeeBilisim.Web.Models
@model List<HakkimizdaModel>
@{
    Layout = "";

}

<br>
<h2 class="text-center">KENDİMİZİ TANITALIM BİLGİSİ</h2>
<br />
<table class="table table-bordered col-md-12">
    <thead>
        <tr>
            <th scope="col">Kişi 1</th>
            <th scope="col">Kişi 2</th>
            <th scope="col" style="text-align:center;">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.KendimiziTanitalim1</td>
                <td>@x.KendimiziTanitalim2</td>
                <td style="text-align:center;"><a href="/AdminPanel/KendimiziTanitalimGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>


BeeBilisim.Web/Views/AdminPanel/MesajDetayi.cshtml
@model BeeBilisim.Web.Models.EmailData

@{
    ViewData["Title"] = "MesajDetayi";
    Layout = "~/Views/Shared/_AdminPanelLayout.cshtml";
}


<h2 style="text-align:center;">MESAJ DETAYI</h2> <br />


                <div class="col-md-12">
                    <div class="card card-primary card-outline">
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h4>Konu: @Model.Subject</h4>
                                <h6>
                                    Gönderen:<b> @Model.To</b> 
                                    <span class="mailbox-read-time float-right">@Model.GonderilmeTarihi.ToString("MM/dd/yyyy H:mm")</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->

                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>
                                    @Model.Body
                                </p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>
                        <!-- /.card-body -->
                        <!-- /.card-footer -->
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>





BeeBilisim.Web/Views/AdminPanel/MisyonumuzPartial.cshtml
@using BeeBilisim.Web.Models
@model List<HakkimizdaModel>
@{
    Layout = "";

}

<br>
<h2 class="text-center">MİSYONUMUZ BİLGİSİ</h2>
<br />
<table class="table table-bordered col-md-12">
    <thead>
        <tr>
            <th scope="col">Misyonumuz Metni</th>
            <th scope="col" style="text-align:center;">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.Misyonumuz</td>
                <td style="text-align:center;"><a href="/AdminPanel/MisyonumuzGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>


BeeBilisim.Web/Views/AdminPanel/NedenBizGoruntule.cshtml
@using BeeBilisim.Web.Models
@model List<AnasayfaModel>
@{
    Layout = "";

}

<br>
<h2 class="text-center">NEDEN BİZ SAYFASI BİLGİLERİ</h2>
<br />
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Neden Biz Metni</th>
            <th scope="col">Neden Biz Sol Taraf 1. Madde</th>
            <th scope="col">Neden Biz Sol Taraf 2. Madde</th>
            <th scope="col">Neden Biz Sol Taraf 3. Madde</th>
            <th scope="col">Neden Biz Sağ Taraf 1. Madde</th>
            <th scope="col">Neden Biz Sağ Taraf 2. Madde</th>
            <th scope="col">Neden Biz Sağ Taraf 3. Madde</th>
            <th scope="col">Neden Biz Sağ Taraf 4. Madde</th>

            <th scope="col">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.NedenBizMetin</td>
                <td>@x.NedenBizSol1</td>
                <td>@x.NedenBizSol2</td>
                <td>@x.NedenBizSol3</td>
                <td>@x.NedenBizSag1</td>
                <td>@x.NedenBizSag2</td>
                <td>@x.NedenBizSag3</td>
                <td>@x.NedenBizSag4</td>
                <td><a href="/AdminPanel/NedenBizGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>


BeeBilisim.Web/Views/AdminPanel/ReferansListesi.cshtml
@using BeeBilisim.Web.Models
@model List<ReferasanslarModel>

@{
    ViewData["Title"] = "ReferansListesi";
    Layout = "~/Views/Shared/_AdminPanelLayout.cshtml";
}


<br>
<h2 class="text-center">SİSTEMDE YÜKLÜ REFERANSLAR</h2>
<br />

<a href="/AdminPanel/ReferansEkle/" class="btn btn-primary">Yeni Referans Ekle</a>
<br />

<br />
<table class="table table-bordered col-md-12">
    <thead>
        <tr style="text-align:center;">
            <th>Referans Website</th>
            <th>Sıra</th>
            <th>Logo</th>
            <th scope="col">Sil</th>
            <th scope="col">Güncelle</th>
        </tr>
    </thead>
    <tbody style="text-align:center;">
        @foreach (var x in Model)
        {
            <tr>
                <td> @x.ReferansWebsite</td>
                <td> @x.Sira</td>
                <td> <img src="@("~/images/"+x.ImageName)" asp-append-version="true" class="text-center" id="foto" /> </td>

                <td><a href="/AdminPanel/ReferansSil/@x.Id" class="btn btn-danger" onclick="return confirm('Silmek istediğinizden emin misiniz?');">Sil</a></td>
                <td><a href="/AdminPanel/ReferanslariGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>

<style>
    #foto {
        border: 1px solid #ddd;
        border-radius: 4px;
        padding: 5px;
        height:150px;
        width:150px;
    }

</style>


BeeBilisim.Web/Views/AdminPanel/SloganGoruntulePartial.cshtml
@using BeeBilisim.Web.Models
@model List<AnasayfaModel>
@{
    Layout = "";

}

<br>
<h2 class="text-center">SLOGAN BİLGİSİ</h2>
<br />
<table class="table table-bordered col-md-12">
    <thead>
        <tr>
            <th scope="col">Slogan Adı</th>
            <th scope="col">Slogan Açıklaması</th>
            <th scope="col">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.Slogan</td>
                <td>@x.SloganAciklama</td>
                <td><a href="/AdminPanel/SloganGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>


BeeBilisim.Web/Views/AdminPanel/TelefonFaxEmailGoruntule.cshtml
@using BeeBilisim.Web.Models
@model List<AnasayfaModel>
@{
    Layout = null;
}

<br>
<h2 class="text-center">TELEFON-FAX-EMAİL BİLGİSİ </h2>
<br />
<table class="table table-bordered col-md-12">
    <thead>
        <tr>
            <th scope="col">Telefon</th>
            <th scope="col">Fax</th>
            <th scope="col">Email</th>
            <th scope="col" >Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.Telefon</td>
                <td>@x.Fax</td>
                <td>@x.Email</td>
                <td ><a href="/AdminPanel/TelefonFaxEmailGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>

BeeBilisim.Web/Views/AdminPanel/TelefonGetir.cshtml
@model BeeBilisim.Web.Models.HakkimizdaModel
@using System.Security.Claims
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor httpContextAccessor
@{
    ViewData["Title"] = "TelefonGetir";
    Layout = "~/Views/Shared/_AdminPanelLayout.cshtml";
    string displayName = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;

}


<h2 class="text-center">TELEFON BİLGİSİ</h2>
@using (Html.BeginForm("TelefonGuncelle", "AdminPanel", FormMethod.Post))
{
    <div class="padding:10px;">
        @Html.HiddenFor(x => x.Id)
        <div>
            <label>Telefon: </label><br />
            @Html.TextBoxFor(q => q.Telefon, new { @class = "form-control" })
        </div>
        <div>
            <input type="hidden" name="LastupUser" value="@displayName">
        </div>
        <div style="margin-top:15px;">
            <button class="btn btn-info">Güncelle</button>
        </div>
    </div>
}


BeeBilisim.Web/Views/AdminPanel/TelefonPartial.cshtml
@using BeeBilisim.Web.Models
@model List<HakkimizdaModel>
@{
    Layout = "";

}

<br>
<h2 class="text-center">TELEFON BİLGİSİ</h2>
<br />
<table class="table table-bordered col-md-12">
    <thead>
        <tr>
            <th scope="col">Telefon)</th>
            <th scope="col" style="text-align:center;">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.Telefon</td>
                <td style="text-align:center;"><a href="/AdminPanel/TelefonGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>


BeeBilisim.Web/Views/AdminPanel/VizyonumuzPartial.cshtml
@using BeeBilisim.Web.Models
@model List<HakkimizdaModel>
@{
    Layout = "";

}

<br>
<h2 class="text-center">VİZYONUMUZ BİLGİSİ</h2>
<br />
<table class="table table-bordered col-md-12">
    <thead>
        <tr>
            <th scope="col">Vizyonumuz Metni</th>
            <th scope="col" style="text-align:center;">Güncelle</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.Vizyonumuz</td>
                <td style="text-align:center;"><a href="/AdminPanel/VizyonumuzGetir/@x.Id" class="btn btn-warning">Güncelle</a></td>
            </tr>
        }
    </tbody>
</table>


BeeBilisim.Web/Views/AdminPanel/YeniKisiEkle.cshtml
@model BeeBilisim.Web.Models.Kullanicilars

@using System.Security.Claims
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor httpContextAccessor

@{
    ViewData["Title"] = "YeniKisiEkle";
    Layout = "~/Views/Shared/_AdminPanelLayout.cshtml";

    string displayName = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Email).Value;

}

<h2>Yeni Kişi Ekle</h2>

@using (Html.BeginForm("YeniKisiEkle", "AdminPanel", FormMethod.Post))
{
    <div>
        <div class="padding:10px;">
            <label>Ad: </label><br />
            @Html.TextBoxFor(q => q.Ad, new { @class = "form-control",required = "required" })
        </div>
        <div>
            <label>Soyad: </label><br />
            @Html.TextBoxFor(q => q.Soyad, new { @class = "form-control",required = "required" })
        </div>
        <div>
            <label>Telefon: </label><br />
            @Html.TextBoxFor(q => q.Telefon, new { @class = "form-control" })
        </div>
        <div>
            <label>Mail: </label><br />
            @Html.TextBoxFor(q => q.Email, new { @class = "form-control",required = "required" })
        </div>
        <div>
            <label>Şifre:</label><br />
            @Html.PasswordFor(q => q.Sifre, new { @class = "form-control",required = "required" })
        </div>
        <div>
            <label>Şifreyi bir kez daha girin:</label><br />
            @Html.PasswordFor(q => q.Sifre2, new { @class = "form-control",required = "required" })
        </div>
        <div>
            <input type="hidden" name="CreateUser" value="@displayName">
        </div>
        <div style="margin-top:15px;">
            <button class="btn btn-primary">Ekle</button>
        </div><br>
        <b>  @ViewBag.hata  </b>
    </div>
}